=== FeatureToggleStudy/OpenConext-manage/mr-server/src/main/resources/metadata_configuration/saml20_idp.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "saml20_idp",
  "definitions": {
    "SingleSignOnService": {
      "type": "string",
      "enum": [
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
        "urn:oasis:names:tc:SAML:2.0:bindings:SOAP",
        "urn:oasis:names:tc:SAML:2.0:bindings:PAOS",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact",
        "urn:oasis:names:tc:SAML:2.0:bindings:URI"
      ],
      "default": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
    },
    "NameIDFormat": {
      "type": "string",
      "enum": [
        "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
        "urn:oasis:names:tc:SAML:2.0:nameid-format:transient",
        "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
      ],
      "default": "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    }
  },
  "type": "object",
  "properties": {
    "entityid": {
      "type": "string"
    },
    "state": {
      "type": "string",
      "enum": [
        "prodaccepted",
        "testaccepted"
      ]
    },
    "allowedall": {
      "type": "boolean"
    },
    "active": {
      "type": "boolean"
    },
    "allowedEntities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "disableConsent": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "metaDataFields": {
      "type": "object",
      "properties": {
        "certData": {
          "type": "string",
          "format": "certificate"
        },
        "certData2": {
          "type": "string",
          "format": "certificate"
        },
        "certData3": {
          "type": "string",
          "format": "certificate"
        },
        "SingleLogoutService_Binding": {
          "type": "string",
          "enum": [
            "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
            "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
            "urn:oasis:names:tc:SAML:2.0:bindings:SOAP",
            "urn:oasis:names:tc:SAML:2.0:bindings:PAOS",
            "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact",
            "urn:oasis:names:tc:SAML:2.0:bindings:URI"
          ],
          "default": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "SingleLogoutService_Location": {
          "type": "string",
          "format": "uri"
        },
        "logo:0:url": {
          "type": "string",
          "format": "uri"
        },
        "logo:0:width": {
          "type": "string",
          "format": "number"
        },
        "logo:0:height": {
          "type": "string",
          "format": "number"
        },
        "redirect.sign": {
          "type": "boolean"
        },
        "coin:publish_in_edugain": {
          "type": "boolean",
          "default": false
        },
        "coin:publish_in_edugain_date": {
          "type": "string",
          "format": "date-time"
        },
        "coin:additional_logging": {
          "type": "boolean"
        },
        "coin:institution_id": {
          "type": "string"
        },
        "coin:institution_guid": {
          "type": "string"
        },
        "coin:guest_qualifier": {
          "type": "string",
          "enum": [
            "All",
            "Some",
            "None"
          ]
        },
        "coin:schachomeorganization": {
          "type": "string"
        },
        "NameIDFormat": {
          "$ref": "#/definitions/NameIDFormat"
        },
        "coin:disable_scoping": {
          "type": "boolean"
        },
        "coin:hidden": {
          "type": "boolean"
        }
      },
      "patternProperties": {
        "^name:(en|nl)$": {
          "type": "string"
        },
        "^displayName:(en|nl)$": {
          "type": "string"
        },
        "^description:(en|nl)$": {
          "type": "string"
        },
        "^contacts:([0-3]{1}):surName$": {
          "type": "string"
        },
        "^contacts:([0-3]{1}):givenName$": {
          "type": "string"
        },
        "^contacts:([0-3]{1}):emailAddress$": {
          "type": "string",
          "format": "email"
        },
        "^contacts:([0-3]{1}):telephoneNumber": {
          "type": "string",
          "format": "string"
        },
        "^contacts:([0-3]{1}):contactType$": {
          "type": "string",
          "enum": [
            "technical",
            "support",
            "administrative",
            "billing",
            "other"
          ]
        },
        "^OrganizationName:(en|nl)$": {
          "type": "string"
        },
        "^OrganizationDisplayName:(en|nl)$": {
          "type": "string"
        },
        "^OrganizationURL:(en|nl)$": {
          "type": "string",
          "format": "uri"
        },
        "^coin:entity_categories:([1-2]{1})$": {
          "type": "string",
          "enum": [
            "http://refeds.org/category/research-and-scholarship",
            "http://refeds.org/category/hide-from-discovery"
          ]
        },
        "^SingleSignOnService:([0-9]{1}):Binding$": {
          "$ref": "#/definitions/SingleSignOnService",
          "multiplicity": 10
        },
        "^SingleSignOnService:([0-9]{1}):Location$": {
          "type": "string",
          "format": "uri",
          "multiplicity": 10
        },
        "^keywords:(en|nl)$": {
          "type": "string"
        },
        "^shibmd:scope:([0-5]{1}):allowed$": {
          "type": "string",
          "multiplicity": 10
        },
        "^shibmd:scope:([0-5]{1}):regexp": {
          "type": "string",
          "multiplicity": 10
        }
      },
      "required": [
        "name:en",
        "SingleSignOnService:0:Binding",
        "SingleSignOnService:0:Location"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "entityid",
    "state",
    "allowedall"
  ],
  "additionalProperties": false,
  "indexes": [
    {
      "name": "autocomplete_text_query",
      "type": "text",
      "fields": [
        "entityid",
        "metaDataFields.name:en",
        "metaDataFields.name:nl",
        "metaDataFields.description:en",
        "metaDataFields.description:nl"
      ]
    }
  ]
}

=== FeatureToggleStudy/OpenConext-manage/mr-server/src/main/resources/metadata_templates/saml20_idp.template.json
{
  "entityid": "",
  "state": "testaccepted",
  "allowedall": true,
  "allowedEntities": [],
  "disableConsent": [],
  "metaDataFields": {
    "name:en": "OpenConext Valid IDP EN",
    "SingleSignOnService:0:Binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
    "SingleSignOnService:0:Location": ""
  }
}
