=== FeatureToggleStudy/OpenConext-manage/manage-server/src/main/resources/metadata_configuration/single_tenant_template.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "single_tenant_template",
  "order": 3,
  "definitions": {
    "AssertionConsumerServiceBinding": {
      "type": "string",
      "enum": [
        "urn:oasis:names:tc:SAML:1.0:profiles:browser-post",
        "urn:oasis:names:tc:SAML:1.0:profiles:artifact-01",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST-SimpleSign",
        "urn:oasis:names:tc:SAML:2.0:bindings:SOAP",
        "urn:oasis:names:tc:SAML:2.0:bindings:PAOS",
        "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact",
        "urn:oasis:names:tc:SAML:2.0:bindings:URI"
      ],
      "default": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
    },
    "ArpAttribute": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "source": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "id": {
      "type": "number"
    },
    "entityid": {
      "type": "string"
    },
    "type": {
      "type": "string",
      "enum": [
        "single-tenant-template"
      ]
    },
    "revisionid": {
      "type": "number"
    },
    "state": {
      "type": "string",
      "enum": [
        "prodaccepted",
        "testaccepted"
      ]
    },
    "metadataurl": {
      "type": [
        "string",
        "null"
      ]
    },
    "allowedall": {
      "type": "boolean"
    },
    "user": {
      "type": "string"
    },
    "created": {
      "type": "string"
    },
    "revisionnote": {
      "type": "string"
    },
    "active": {
      "type": "boolean"
    },
    "allowedEntities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    },
    "arp": {
      "type": "object",
      "sources": [
        "idp",
        "orcid",
        "sab",
        "voot",
        "pseudo_email",
        "surfmarket_entitlements"
      ],
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "attributes": {
          "properties": {
            "urn:mace:dir:attribute-def:eduPersonTargetedID": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:eduPersonPrincipalName": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:displayName": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:cn": {
              "$ref": "#/definitions/ArpAttribute",
              "description": "common name"
            },
            "urn:mace:dir:attribute-def:givenName": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:sn": {
              "$ref": "#/definitions/ArpAttribute",
              "description": "surname"
            },
            "urn:mace:dir:attribute-def:mail": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:terena.org:attribute-def:schacHomeOrganization": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:terena.org:attribute-def:schacHomeOrganizationType": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:schac:attribute-def:schacPersonalUniqueCode": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:eduPersonAffiliation": {
              "$ref": "#/definitions/ArpAttribute",
              "multiplicity": true
            },
            "urn:mace:dir:attribute-def:eduPersonScopedAffiliation": {
              "$ref": "#/definitions/ArpAttribute",
              "multiplicity": true
            },
            "urn:mace:dir:attribute-def:eduPersonEntitlement": {
              "$ref": "#/definitions/ArpAttribute",
              "multiplicity": true
            },
            "urn:mace:dir:attribute-def:eduPersonOrcid": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:isMemberOf": {
              "$ref": "#/definitions/ArpAttribute",
              "multiplicity": true
            },
            "urn:mace:dir:attribute-def:uid": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:dir:attribute-def:preferredLanguage": {
              "$ref": "#/definitions/ArpAttribute"
            },
            "urn:mace:surffederatie.nl:attribute-def:nlEduPersonOrgUnit": {
              "$ref": "#/definitions/ArpAttribute",
              "deprecated": true,
              "multiplicity": true
            },
            "urn:mace:surffederatie.nl:attribute-def:nlEduPersonStudyBranch": {
              "$ref": "#/definitions/ArpAttribute",
              "deprecated": true,
              "multiplicity": true
            },
            "urn:mace:surffederatie.nl:attribute-def:nlStudielinkNummer": {
              "$ref": "#/definitions/ArpAttribute",
              "deprecated": true
            },
            "urn:mace:surffederatie.nl:attribute-def:nlDigitalAuthorIdentifier": {
              "$ref": "#/definitions/ArpAttribute",
              "deprecated": true
            },
            "urn:oid:1.3.6.1.4.1.1076.20.40.40.1": {
              "$ref": "#/definitions/ArpAttribute",
              "displayName": "collabPersonId",
              "deprecated": true
            }
          }
        }
      }
    },
    "notes": {
      "type": [
        "string",
        "null"
      ]
    },
    "metaDataFields": {
      "type": "object",
      "properties": {
        "mdrpi:RegistrationInfo": {
          "type": "string"
        },
        "logo:0:url": {
          "type": "string",
          "format": "url"
        },
        "logo:0:width": {
          "type": "string",
          "format": "number"
        },
        "logo:0:height": {
          "type": "string",
          "format": "number"
        },
        "redirect.sign": {
          "type": "string",
          "format": "boolean"
        },
        "coin:publish_in_edugain": {
          "type": "string",
          "format": "boolean",
          "default": false
        },
        "coin:publish_in_edugain_date": {
          "type": "string",
          "format": "date-time"
        },
        "coin:interfed_source": {
          "type": "string",
          "enum": [
            "Entree",
            "eduGAIN"
          ]
        },
        "coin:additional_logging": {
          "type": "string",
          "format": "boolean"
        },
        "coin:institution_id": {
          "type": "string"
        },
        "coin:institution_guid": {
          "type": "string",
          "format": "uuid"
        },
        "coin:trusted_proxy": {
          "type": "string",
          "format": "boolean",
          "default": "false"
        },
        "coin:no_consent_required": {
          "type": "string",
          "format": "boolean",
          "info": "Select this option to skip the consent for a user after the first login."
        },
        "coin:eula": {
          "type": "string",
          "format": "url"
        },
        "coin:application_url": {
          "type": "string",
          "format": "url"
        },
        "coin:original_metadata_url": {
          "type": "string",
          "format": "url"
        },
        "coin:service_team_id": {
          "type": "string"
        },
        "coin:privacy:what_data": {
          "type": "string"
        },
        "coin:privacy:access_data": {
          "type": "string"
        },
        "coin:privacy:country": {
          "type": "string"
        },
        "coin:privacy:security_measures": {
          "type": "string"
        },
        "coin:privacy:certification": {
          "type": "string",
          "format": "boolean"
        },
        "coin:privacy:certification_location": {
          "type": "string"
        },
        "coin:privacy:certification_valid_from": {
          "type": "string",
          "format": "number"
        },
        "coin:privacy:certification_valid_to": {
          "type": "string",
          "format": "number"
        },
        "coin:privacy:surfmarket_dpa_agreement": {
          "type": "string",
          "format": "boolean"
        },
        "coin:privacy:surfnet_dpa_agreement": {
          "type": "string",
          "format": "boolean"
        },
        "coin:privacy:sn_dpa_why_not": {
          "type": "string"
        },
        "coin:privacy:privacy_policy": {
          "type": "string",
          "format": "boolean"
        },
        "coin:privacy:privacy_policy_url": {
          "type": "string",
          "format": "url"
        },
        "coin:privacy:other_info": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonTargetedID": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonPrincipalName": {
          "type": "string"
        },
        "coin:attr_motivation:displayName": {
          "type": "string"
        },
        "coin:attr_motivation:cn": {
          "type": "string"
        },
        "coin:attr_motivation:givenName": {
          "type": "string"
        },
        "coin:attr_motivation:sn": {
          "type": "string"
        },
        "coin:attr_motivation:mail": {
          "type": "string"
        },
        "coin:attr_motivation:schacHomeOrganization": {
          "type": "string"
        },
        "coin:attr_motivation:schacHomeOrganizationType": {
          "type": "string"
        },
        "coin:attr_motivation:schacPersonalUniqueCode": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonAffiliation": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonScopedAffiliation": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonEntitlement": {
          "type": "string"
        },
        "coin:attr_motivation:eduPersonOrcid": {
          "type": "string"
        },
        "coin:attr_motivation:isMemberOf": {
          "type": "string"
        },
        "coin:attr_motivation:uid": {
          "type": "string"
        },
        "coin:attr_motivation:preferredLanguage": {
          "type": "string"
        }
      },
      "patternProperties": {
        "^name:(en|nl)$": {
          "type": "string"
        },
        "^displayName:(en|nl)$": {
          "type": "string"
        },
        "^description:(en|nl)$": {
          "type": "string"
        },
        "^contacts:([0-3]{1}):surName$": {
          "type": "string",
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^contacts:([0-3]{1}):givenName$": {
          "type": "string",
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^contacts:([0-3]{1}):emailAddress$": {
          "type": "string",
          "format": "email",
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^contacts:([0-3]{1}):telephoneNumber$": {
          "type": "string",
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^contacts:([0-3]{1}):isSirtfiSecurityContact$": {
          "type": "string",
          "format": "boolean",
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^contacts:([0-3]{1}):contactType$": {
          "type": "string",
          "enum": [
            "technical",
            "support",
            "administrative",
            "billing",
            "other"
          ],
          "multiplicity": 4,
          "sibblingIndependent": true
        },
        "^OrganizationName:(en|nl)$": {
          "type": "string"
        },
        "^OrganizationDisplayName:(en|nl)$": {
          "type": "string"
        },
        "^OrganizationURL:(en|nl)$": {
          "type": "string",
          "format": "url"
        },
        "^url:(en|nl)$": {
          "type": "string",
          "format": "url"
        },
        "^mdui:PrivacyStatementURL:(en|nl)$": {
          "type": "string",
          "format": "url"
        },
        "^mdrpi:RegistrationPolicy:(en|nl)$": {
          "type": "string"
        },
        "^coin:entity_categories:([1-2]{1})$": {
          "type": "string",
          "enum": [
            "http://refeds.org/category/research-and-scholarship",
            "http://refeds.org/category/hide-from-discovery",
            "http://www.geant.net/uri/dataprotection-code-of-conduct/v1"
          ],
          "multiplicity": 2,
          "startIndex": 1
        }
      },
      "required": [
        "name:en"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "state",
    "metaDataFields"
  ],
  "additionalProperties": false,
  "indexes": [
    {
      "name": "field_entityid",
      "type": "field",
      "fields": [
        "entityid"
      ],
      "unique": false
    }
  ]
}

=== FeatureToggleStudy/OpenConext-manage/mr-server/src/main/resources/metadata_templates/saml20_sp.template.json
{
  "entityid": "",
  "state": "testaccepted",
  "allowedall": true,
  "arp": {
    "enabled": false,
    "_class": "mr.migration.ArpAttributes",
    "attributes": {}
  },
  "metaDataFields": {
    "name:en": "",
    "AssertionConsumerService:0:Binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST",
    "AssertionConsumerService:0:Location": "",
    "NameIDFormat": "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
  },
  "allowedEntities": []
}
